title: Jodie Chin # your name (or website title) here
logo: "/images/IMG_7730.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UC Berkeley B.A. Applied Mathematics 2020 
  <br><br>
  Student Data Analyst for Cal Athletics
  <br><br>
  
  <a href="https://www.linkedin.com/in/jodie-chin/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
